export const translations = {
    pt: {
        // Common
        home: 'Início',
        presentations: 'Apresentações',
        designs: 'Designs',
        photos: 'Fotografias',
        videos: 'Vídeos',
        about_me: 'Sobre Mim',
        contact: 'Contactos',
        toggle_navigation: 'Alternar navegação',
        close: 'Fechar',
        all_rights_reserved: '&copy; 2025 Beatriz Rodrigues. Todos os direitos reservados.',
        loading_content: 'A carregar conteúdo...',
        no_content_found: 'Nenhum conteúdo para \'{type}\' encontrado.',
        error_loading_content: 'Erro ao carregar {type}. Por favor, tente novamente mais tarde.',
        
        // Home page (examples)
        project_a_title: 'Projecto A',
        project_a_description: 'Um trabalho inovador que combina design e tecnologia.',
        short_film_title: 'Filme Curto "O Regresso"',
        short_film_description: 'Uma narrativa visual emocionante e envolvente.',
        corporate_presentation_title: 'Apresentação Corporativa',
        corporate_presentation_description: 'Estratégias de marketing para o futuro.',
        best_works: 'Melhores Trabalhos',
        urban_documentary_title: 'Documentário Urbano',
        urban_documentary_description: 'Uma exploração profunda da vida na cidade, com entrevistas e imagens cativantes.',
        natural_landscapes_title: 'Paisagens Naturais',
        natural_landscapes_description: 'Coleção de fotografias que capturam a beleza intocada da natureza.',
        innovation_workshop_title: 'Workshop de Inovação',
        innovation_workshop_description: 'Uma apresentação interativa sobre as últimas tendências em inovação tecnológica.',
        graphic_design_creations_title: 'Criações em Design Gráfico',
        graphic_design_creations_description: 'Designs criativos desenvolvidos em várias ferramentas, incluindo Canva.',
        view_video: 'Ver Vídeo',
        view_photos: 'Ver Fotografias',
        view_presentation: 'Ver Apresentação',
        view_designs: 'Ver Designs',
        discover_more: 'Descobrir Mais',
        videos_thumb_desc: 'Criações audiovisuais que contam histórias.',
        photos_thumb_desc: 'Galeria de imagens que capturam momentos únicos.',
        presentations_thumb_desc: 'Projetos e ideias transformados em apresentações impactantes.',
        designs_thumb_desc: 'Elementos gráficos criativos e layouts profissionais.',

        // About Me Page
        about_me_page_title: 'Beatriz Rodrigues - Sobre Mim',
        about_me_section_title: 'Sobre Mim',
        about_me_greeting: 'Olá, sou a Beatriz!',
        about_me_paragraph_1: 'Sou uma criadora de conteúdo apaixonada por transformar ideias em realidade visual. Com uma base sólida em comunicação e uma curiosidade insaciável por novas tecnologias, dedico-me a criar apresentações, designs, fotografias e vídeos que não só informam, mas também inspiram e envolvem.',
        about_me_paragraph_2: 'A minha jornada começou com uma simples câmara e um desejo de contar histórias. Hoje, essa paixão evoluiu para um conjunto de competências diversificado que me permite abordar projetos de diferentes ângulos, sempre com um foco na clareza, estética e impacto.',
        about_me_paragraph_3: 'Neste portfólio, encontrará uma seleção dos meus trabalhos que refletem o meu percurso e a minha dedicação. Vamos criar algo incrível juntos!',

        // Contact Page
        contact_page_title: 'Beatriz Rodrigues - Contactos',
        contact_section_title: 'Contacte-me',
        contact_section_description: 'Se tiver alguma questão, projeto em mente ou simplesmente quiser dizer olá, utilize o formulário abaixo ou os contactos alternativos.',
        send_message_title: 'Envie uma Mensagem',
        form_name_label: 'Nome:',
        form_name_placeholder: 'O seu nome',
        form_email_label: 'Email:',
        form_email_placeholder: 'O seu email',
        form_message_label: 'Mensagem:',
        form_message_placeholder: 'A sua mensagem',
        send_message_button: 'Enviar Mensagem',
        alternative_contact_title: 'Informações de Contacto Alternativas',
        alternative_contact_intro: 'Pode também contactar-me através dos seguintes meios:',
        phone_number: '+351 925 451 131',
        whatsapp_link_text: 'Enviar mensagem',
        contact_note: 'Responderei o mais breve possível. Agradeço o seu interesse!',
        
        // Gallery Pages
        photos_page_title: 'Beatriz Rodrigues - Fotografias',
        photos_section_title: 'Fotografias',
        photos_section_description: 'Explora algumas das fotografias captadas ao longo do meu percurso.',
        photo_title: 'Título da Foto',
        photo_description: 'Descrição da Foto.',

        designs_page_title: 'Beatriz Rodrigues - Designs',
        designs_section_title: 'Meus Designs',
        designs_section_description: 'Explore uma variedade de projetos de design gráfico e digital que demonstram a minha criatividade e habilidades.',
        design_title: 'Título do Design',
        design_description: 'Descrição do Design.',
        loading_designs: 'A carregar designs...',

        videos_page_title: 'Beatriz Rodrigues - Vídeos',
        videos_section_title: 'Meus Vídeos',
        videos_section_description: 'Uma seleção de vídeos que demonstram os meus projetos, apresentações e momentos captados.',
        video_title: 'Título do Vídeo',

        presentations_page_title: 'Beatriz Rodrigues - Apresentações',
        presentations_section_title: 'Minhas Apresentações',
        presentations_section_description: 'Uma coleção das minhas palestras, workshops e portfólios de apresentação, incorporados diretamente para sua visualização.',
        loading_presentations: 'A carregar apresentações...',
        no_presentations_found: 'Não foram encontradas apresentações.',
    },
    en: {
        // Common
        home: 'Home',
        presentations: 'Presentations',
        designs: 'Designs',
        photos: 'Photos',
        videos: 'Videos',
        about_me: 'About Me',
        contact: 'Contact',
        toggle_navigation: 'Toggle navigation',
        close: 'Close',
        all_rights_reserved: '&copy; 2025 Beatriz Rodrigues. All rights reserved.',
        loading_content: 'Loading content...',
        no_content_found: 'No content for \'{type}\' found.',
        error_loading_content: 'Error loading {type}. Please try again later.',

        // Home page (examples)
        project_a_title: 'Project A',
        project_a_description: 'An innovative work that combines design and technology.',
        short_film_title: 'Short Film "The Return"',
        short_film_description: 'An emotional and engaging visual narrative.',
        corporate_presentation_title: 'Corporate Presentation',
        corporate_presentation_description: 'Marketing strategies for the future.',
        best_works: 'Best Works',
        urban_documentary_title: 'Urban Documentary',
        urban_documentary_description: 'A deep exploration of city life, with captivating interviews and footage.',
        natural_landscapes_title: 'Natural Landscapes',
        natural_landscapes_description: 'A collection of photographs that capture the untouched beauty of nature.',
        innovation_workshop_title: 'Innovation Workshop',
        innovation_workshop_description: 'An interactive presentation on the latest trends in technological innovation.',
        graphic_design_creations_title: 'Graphic Design Creations',
        graphic_design_creations_description: 'Creative designs developed using various tools, including Canva.',
        view_video: 'View Video',
        view_photos: 'View Photos',
        view_presentation: 'View Presentation',
        view_designs: 'View Designs',
        discover_more: 'Discover More',
        videos_thumb_desc: 'Audiovisual creations that tell stories.',
        photos_thumb_desc: 'A gallery of images capturing unique moments.',
        presentations_thumb_desc: 'Projects and ideas transformed into impactful presentations.',
        designs_thumb_desc: 'Creative graphic elements and professional layouts.',

        // About Me Page
        about_me_page_title: 'Beatriz Rodrigues - About Me',
        about_me_section_title: 'About Me',
        about_me_greeting: 'Hello, I\'m Beatriz!',
        about_me_paragraph_1: 'I\'m a content creator passionate about turning ideas into visual reality. With a solid foundation in communication and an insatiable curiosity for new technologies, I dedicate myself to creating presentations, designs, photographs, and videos that not only inform but also inspire and engage.',
        about_me_paragraph_2: 'My journey began with a simple camera and a desire to tell stories. Today, this passion has evolved into a diverse set of skills that allows me to approach projects from different angles, always focusing on clarity, aesthetics, and impact.',
        about_me_paragraph_3: 'In this portfolio, you\'ll find a selection of my works that reflect my journey and dedication. Let\'s create something amazing together!',

        // Contact Page
        contact_page_title: 'Beatriz Rodrigues - Contact',
        contact_section_title: 'Get in Touch',
        contact_section_description: 'If you have any questions, a project in mind, or simply want to say hello, use the form below or the alternative contacts.',
        send_message_title: 'Send a Message',
        form_name_label: 'Name:',
        form_name_placeholder: 'Your name',
        form_email_label: 'Email:',
        form_email_placeholder: 'Your email',
        form_message_label: 'Message:',
        form_message_placeholder: 'Your message',
        send_message_button: 'Send Message',
        alternative_contact_title: 'Alternative Contact Information',
        alternative_contact_intro: 'You can also contact me through the following means:',
        phone_number: '+351 925 451 131',
        whatsapp_link_text: 'Send message',
        contact_note: 'I will respond as soon as possible. Thank you for your interest!',

        // Gallery Pages
        photos_page_title: 'Beatriz Rodrigues - Photos',
        photos_section_title: 'Photos',
        photos_section_description: 'Explore some of the photographs captured throughout my journey.',
        photo_title: 'Photo Title',
        photo_description: 'Photo Description.',

        designs_page_title: 'Beatriz Rodrigues - Designs',
        designs_section_title: 'My Designs',
        designs_section_description: 'Explore a variety of graphic and digital design projects that demonstrate my creativity and skills.',
        design_title: 'Design Title',
        design_description: 'Design Description.',
        loading_designs: 'Loading designs...',

        videos_page_title: 'Beatriz Rodrigues - Videos',
        videos_section_title: 'My Videos',
        videos_section_description: 'A selection of videos showcasing my projects, presentations, and captured moments.',
        video_title: 'Video Title',
        
        presentations_page_title: 'Beatriz Rodrigues - Presentations',
        presentations_section_title: 'My Presentations',
        presentations_section_description: 'A collection of my lectures, workshops, and presentation portfolios, embedded directly for your viewing.',
        loading_presentations: 'Loading presentations...',
        no_presentations_found: 'No presentations found.',
    }
};

