name: Enviar Newsletter Manual

on:
  workflow_dispatch:
    inputs:
      subject:
        description: 'O Assunto do E-mail da Newsletter'
        required: true
        default: 'Novidades no meu Portfólio!'
      message:
        description: 'Uma pequena mensagem sobre as novidades (ex: Adicionei novas fotos de Coimbra!)'
        required: true

jobs:
  send-newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install axios

      - name: Criar e Enviar Newsletter
        run: node ./.github/workflows/send-newsletter.js
        env:
          MAILERLITE_API_KEY: ${{ secrets.MAILERLITE_API_KEY }}
          NEWSLETTER_SUBJECT: ${{ github.event.inputs.subject }}
          NEWSLETTER_MESSAGE: ${{ github.event.inputs.message }}