# Ficheiro: .github/workflows/sync.yml (VERSÃO FINAL E CORRIGIDA)

name: Sincronizar Media, Gerar Dados e Manifesto

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19,20 * * *'

permissions:
  contents: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Europe/Lisbon'
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar ferramentas e dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg jq libjpeg-dev zlib1g-dev libtiff5-dev libwebp-dev libfreetype6-dev
          curl https://rclone.org/install.sh | sudo bash
          pip3 install --no-cache-dir --force-reinstall Pillow

      - name: Verificar funcionalidades do Pillow
        run: |
          echo "A verificar o suporte a formatos no Pillow:"
          python3 -c "from PIL import features; print(features.pilinfo())"

      - name: Configurar rclone
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf

      - name: Sincronizar Google Drive para Cloudflare R2
        run: |
          echo "--- Sincronizando Drive -> R2 (protegendo a pasta Thumbnails) ---"
          rclone sync "Drive:Portfólio Bia" "R2:bia-portfolio-assets" --exclude "/Thumbnails/**" --exclude "desktop.ini" -v

      - name: Processar Media, Gerar Thumbnails e Ficheiros de Dados
        run: |
          echo "--- Executando o script principal de processamento e geração de dados ---"
          if [ ! -f scripts/Montserrat-SemiBold.ttf ]; then
            mkdir -p scripts/
            curl -L -o scripts/Montserrat-SemiBold.ttf "https://github.com/google/fonts/raw/main/ofl/montserrat/static/Montserrat-SemiBold.ttf"
          fi
          # CORREÇÃO: Executa o script como um módulo para garantir que os imports funcionam
          python3 -m scripts.process_files

      - name: Fazer commit e push de alterações
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json r2_file_manifest.txt
          # CORREÇÃO: Adiciona o log de erros apenas se ele existir, para evitar falhas
          if [ -f upload_errors.log ]; then
            git add upload_errors.log
          fi
          if ! git diff --quiet --exit-code --cached; then
            git commit -m "Atualiza data.json, manifesto e logs de erro [skip ci]"
            git pull --rebase
            git push
          else
            echo "Nenhuma alteração para fazer commit."
          fi