name: Sync, Process and Deploy Portfolio Assets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache APT packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/sync.yml') }}

      - name: Install System Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg jq libjpeg-dev zlib1g-dev libtiff5-dev libwebp-dev libfreetype6-dev curl unzip

      - name: Install Rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache Pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Setup Rclone Config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      - name: Sync from Drive to Local
        run: |
          mkdir -p ./portfolio_source
          rclone copy "Drive:Portfólio Bia" ./portfolio_source -v --exclude "/Thumbnails/**" --exclude "desktop.ini"

      - name: Process Assets
        run: python scripts/process_assets.py

      - name: Sync Processed Files to R2
        run: |
          # Sincroniza apenas os ficheiros processados com sucesso
          rclone sync ./processed_assets "R2:bia-portfolio-assets" -v --fast-list --checksum

      - name: Upload Failed Images as Artifact
        if: always() # Executa este passo mesmo que os passos anteriores falhem
        uses: actions/upload-artifact@v4
        with:
          name: failed-images
          path: ./failed_images/ # Caminho para o diretório com as imagens falhadas
          retention-days: 7
