# .github/workflows/sync.yml
name: Sincronizar Ficheiros, Gerar JSON e Atualizar Site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

permissions:
  contents: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar rclone
        run: sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Configurar rclone
        env:
          RCLONE_CONF_DATA: ${{ secrets.RCLONE_CONF }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF_DATA" > ~/.config/rclone/rclone.conf

      # --- CORREÇÃO 1: Caminhos de origem e destino corrigidos ---
      - name: Sincronizar Google Drive para Cloudflare R2
        run: |
          # Sincroniza a pasta "Portfólio Bia" do Drive para o bucket "bia-portfolio-assets" no R2
          rclone sync "Drive:Portfólio Bia" "R2:bia-portfolio-assets" --progress --exclude "desktop.ini"

      - name: Instalar FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # --- CORREÇÃO 2: Caminhos corrigidos na geração de thumbnails ---
      - name: Gerar e Sincronizar Thumbnails
        id: generate_thumbs # Adiciona um ID a este passo
        run: |
          echo "A iniciar a geração de thumbnails..."
          mkdir -p temp_thumbs
          
          # Instala o jq, uma ferramenta para processar JSON
          sudo apt-get install -y jq

          # Usa rclone lsjson para obter uma lista segura de ficheiros
          # e o jq para extrair os nomes, tratando caracteres especiais
          rclone lsjson "R2:bia-portfolio-assets/Vídeos" | jq -r '.[] | .Path' | while IFS= read -r video_path; do
            
            if [ -z "$video_path" ]; then
              continue
            fi

            video_filename=$(basename "$video_path")
            echo "A processar ficheiro: ${video_filename}"
            
            thumb_basename=$(echo "$video_filename" | sed 's/\.[^.]*$//')
            thumb_filename="${thumb_basename}.jpg"
            local_thumb_path="temp_thumbs/${thumb_filename}"
            
            # Verifica se a thumbnail já existe no R2
            if ! rclone lsf "R2:bia-portfolio-assets/thumbs/" | grep -q "^${thumb_filename}$"; then
              echo "A gerar thumbnail para: ${video_filename}"
              
              temp_video_file="temp_${RANDOM}.mp4"
              
              if rclone copyto "R2:bia-portfolio-assets/${video_path}" "$temp_video_file"; then
                ffmpeg -i "$temp_video_file" -ss 00:00:01 -vframes 1 "$local_thumb_path"
                echo "Thumbnail gerada com sucesso."
                rm "$temp_video_file"
              else
                echo "AVISO: Falha ao descarregar ${video_filename} do R2. A ignorar."
              fi
            else
              echo "Thumbnail para ${video_filename} já existe. A ignorar."
            fi
          done

          echo "Sincronização de thumbnails para o R2..."
          rclone sync temp_thumbs/ "R2:bia-portfolio-assets/thumbs/"