# .github/workflows/sync.yml

name: Processar e Sincronizar Portfólio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-and-process:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar e fazer cache de dependências Apt
        uses: awalsh128/cache-apt-pkgs-action@v1.5.0
        with:
          packages: ffmpeg libimage-exiftool-perl libblas3
          version: 1.0

      - name: Cache para dependências Pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache para Ativos Processados
        id: processed-assets-cache
        uses: actions/cache@v4
        with:
          path: processed_assets
          key: ${{ runner.os }}-processed-assets-${{ hashFiles('**/r2_file_manifest.txt') }}
          restore-keys: |
            ${{ runner.os }}-processed-assets-

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install opencv-python-headless

      - name: Instalar e Configurar Rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          cat << EOF > ~/.config/rclone/rclone.conf
          ${{ secrets.RCLONE_CONF }}
          EOF
          
      - name: Executar Pipeline Principal
        run: python3 main.py

      # --- ATUALIZADO: Lógica de Sincronização em Dois Passos ---

      - name: Passo 1 - Sincronizar Ativos Principais (excluindo Thumbnails )
        run: |
          echo "A sincronizar ativos principais (Vídeos, Fotografias, etc.) para o R2..."
          rclone sync processed_assets/ R2:bia-portfolio-assets \
            --exclude "/Thumbnails/**" \
            --progress -v --track-renames

      - name: Passo 2 - Sincronizar Apenas as Thumbnails para a Raiz
        run: |
          echo "A sincronizar Thumbnails para a pasta 'Thumbnails' na raiz do R2..."
          # Sincroniza o conteúdo de 'processed_assets/Thumbnails' para 'R2:bia-portfolio-assets/Thumbnails'
          rclone sync processed_assets/Thumbnails/ R2:bia-portfolio-assets/Thumbnails \
            --progress -v --track-renames

      - name: Gerar Manifesto de Ficheiros do R2
        run: |
          echo "A gerar o manifesto de ficheiros a partir do R2..."
          rclone lsf -R R2:bia-portfolio-assets > r2_file_manifest.txt

      - name: Fazer Commit e Push dos Ficheiros de Manifesto para o Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json r2_file_manifest.txt || echo "Nenhum ficheiro de manifesto para adicionar."
          
          if ! git diff --staged --quiet; then
            git commit -m "CI: Atualiza data.json e manifesto R2 [skip ci]"
            git push
          else
            echo "Nenhuma alteração nos ficheiros de manifesto para fazer commit."
          fi
