name: Transferir do Drive, Processar e Enviar para o R2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  process-and-transfer:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Instalar e Configurar Rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf
          echo "Configuração do rclone concluída."

      - name: Verificar acesso aos remotes
        run: |
          echo "Verificando remotes configurados..."
          rclone listremotes
          echo "Verificação concluída."

      - name: Executar o Pipeline (Download do Drive -> Processar )
        run: python3 run_processing.py

      - name: Sincronizar Ficheiros Processados para o R2
        run: |
          echo "Iniciando upload dos ficheiros processados para o R2..."
          # O caminho de destino é lido do ficheiro de configuração pelo script,
          # mas aqui usamos diretamente para o upload final.
          rclone sync processed_assets/ R2:bia-portfolio-assets-watermarked --exclude "*.log" -v
          echo "Upload concluído."
