name: Sincronizar Drive, Gerar Thumbs e Dados

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *' # Executa todos os dias às 20:00 UTC

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar rclone e outras ferramentas
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone ffmpeg jq
          
      - name: Configurar rclone
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf

          
      - name: Sincronizar Google Drive para Cloudflare R2
        run: |
          echo "A sincronizar Google Drive para R2..."
          rclone sync "Drive:Portfólio Bia" "R2:bia-portfolio-assets" --exclude "desktop.ini" -P
          echo "Sincronização concluída."

      - name: Gerar e Sincronizar Thumbnails com Metadados
        run: |
          echo "A iniciar a geração de thumbnails e metadados..."
          mkdir -p temp_thumbs

          # Processa os vídeos
          rclone lsf "R2:bia-portfolio-assets/Vídeos" --files-only | while read -r video_file; do
            echo "A processar vídeo: ${video_file}"
            rclone copyto "R2:bia-portfolio-assets/Vídeos/${video_file}" "./${video_file}"
            
            if [ -f "./${video_file}" ]; then
              dims=$(ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 "./${video_file}")
              width=$(echo $dims | cut -d'x' -f1)
              height=$(echo $dims | cut -d'x' -f2)
              echo "Dimensões do vídeo: ${width}x${height}"

              # --- COMANDO CORRIGIDO AQUI ---
              # Usa 'metadata set' para adicionar os metadados
              rclone metadata set "R2:bia-portfolio-assets/Vídeos/${video_file}" --metadata "width=${width},height=${height}"
              
              thumb_name="${video_file%.*}.jpg"
              ffmpeg -i "./${video_file}" -ss 00:00:01.00 -frames:v 1 "temp_thumbs/${thumb_name}"
              rm "./${video_file}"
            else
              echo "AVISO: Falha ao descarregar ${video_file}. A ignorar."
            fi
          done
          
          rclone sync temp_thumbs "R2:bia-portfolio-assets/_thumbnails" -P
          
          # Processa as imagens
          for dir in Fotografias Designs; do
            rclone lsf "R2:bia-portfolio-assets/${dir}" --files-only | while read -r img_file; do
                echo "A processar imagem: ${img_file}"
                rclone copyto "R2:bia-portfolio-assets/${dir}/${img_file}" "./${img_file}"
                if [ -f "./${img_file}" ]; then
                    dims=$(ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 "./${img_file}")
                    width=$(echo $dims | cut -d'x' -f1)
                    height=$(echo $dims | cut -d'x' -f2)
                    echo "Dimensões da imagem: ${width}x${height}"
                    
                    # --- COMANDO CORRIGIDO AQUI ---
                    rclone metadata set "R2:bia-portfolio-assets/${dir}/${img_file}" --metadata "width=${width},height=${height}"
                    
                    rm "./${img_file}"
                fi
            done
          done


      - name: Gerar o ficheiro data.json
        run: |
          echo "A gerar data.json..."
          python3 scripts/process_files.py
          echo "data.json gerado."

      - name: Fazer commit e push do data.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          git diff --quiet --exit-code --cached || git commit -m "Atualiza data.json [skip ci]"
          git push
