name: Sincronizar Drive, Gerar Thumbs e Dados

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

permissions:
  contents: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar ferramentas e dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg jq
          pip3 install Pillow
          curl https://rclone.org/install.sh | sudo bash

      - name: Configurar rclone
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf

      - name: Sincronizar Google Drive para Cloudflare R2
        run: |
          echo "--- Sincronizando ficheiros de origem do Drive para o R2 ---"
          # Este passo agora APAGA os ficheiros processados (wm_* ) que já não têm origem no Drive
          rclone sync "Drive:Portfólio Bia" "R2:bia-portfolio-assets" --exclude "desktop.ini" -v

      - name: Gerar Thumbnails para Vídeos
        run: |
          echo "--- Gerando thumbnails para os vídeos existentes ---"
          mkdir -p temp_thumbs
          # Gera thumbnails APENAS para os vídeos que existem ATUALMENTE no R2
          for video_file in $(rclone lsf "R2:bia-portfolio-assets/Vídeos" --files-only --exclude "wm_*" ); do
            echo "A processar vídeo para thumbnail: ${video_file}"
            rclone copyto "R2:bia-portfolio-assets/Vídeos/${video_file}" "./${video_file}"
            if [ -f "./${video_file}" ]; then
              thumb_name="${video_file%.*}.jpg"
              ffmpeg -i "./${video_file}" -ss 00:00:01.00 -frames:v 1 -update 1 "temp_thumbs/${thumb_name}" > /dev/null 2>&1
              rm "./${video_file}"
            fi
          done
          
          # ** INÍCIO DA ALTERAÇÃO CRÍTICA **
          echo "--- Sincronizando pasta de thumbnails para limpar as antigas ---"
          # Este comando garante que a pasta Thumbnails no R2 tem EXATAMENTE as mesmas
          # thumbnails que acabámos de gerar na pasta local temp_thumbs.
          # Se uma thumbnail existir no R2 mas não em temp_thumbs, será APAGADA.
          rclone sync temp_thumbs "R2:bia-portfolio-assets/Thumbnails" -P
          # ** FIM DA ALTERAÇÃO CRÍTICA **

      - name: Gerar data.json e aplicar Marcas de Água
        run: |
          echo "--- Executando script Python para processar media e gerar data.json ---"
          mkdir -p scripts/
          curl -L -o scripts/Montserrat.ttf "https://github.com/google/fonts/raw/main/ofl/montserrat/Montserrat%5Bwght%5D.ttf"
          python3 scripts/process_files.py

      - name: Fazer commit e push do data.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          if ! git diff --quiet --exit-code --cached; then
            git commit -m "Atualiza data.json e media [skip ci]"
            git pull --rebase
            git push
          else
            echo "Nenhuma alteração no data.json para fazer commit."
          fi
