# .github/workflows/sync.yml (Versão Final e Robusta)
name: Sincronizar Ficheiros, Gerar JSON e Atualizar Site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

permissions:
  contents: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar rclone
        run: sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Configurar rclone
        env:
          RCLONE_CONF_DATA: ${{ secrets.RCLONE_CONF }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF_DATA" > ~/.config/rclone/rclone.conf

      - name: Sincronizar Google Drive para Cloudflare R2
        run: |
          rclone sync "Drive:Portfólio Bia" "R2:bia-portfolio-assets" --progress --exclude "desktop.ini"

      # --- NOVO PASSO ÚNICO PARA PROCESSAMENTO ---
      - name: Instalar dependências (Python e FFmpeg )
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          pip3 install rclone-python

      - name: Gerar Thumbnails e Ficheiro data.json
        run: python3 scripts/process_files.py # Vamos criar este novo ficheiro

      - name: Fazer commit e push do data.json
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@users.noreply.github.com'
          git add data.json
          if ! git diff --staged --quiet; then
            git commit -m "Atualizar data.json com novos ficheiros e thumbnails"
            git push
          else
            echo "Nenhuma alteração no data.json. Nada para fazer commit."
          fi
