name: Sincronizar Drive, Gerar Thumbs e Dados

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

permissions:
  contents: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar ferramentas e dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg jq
          pip3 install Pillow
          curl https://rclone.org/install.sh | sudo bash

      - name: Configurar rclone
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf

      - name: Copiar ficheiros novos ou atualizados do Drive para o R2
        run: |
          echo "--- Copiando ficheiros do Drive para o R2 (não apaga nada ) ---"
          rclone copy "Drive:Portfólio Bia" "R2:bia-portfolio-assets" --exclude "desktop.ini" -v

      # --- SECÇÃO CORRIGIDA ---
      - name: Gerar Thumbnails para Vídeos
        run: |
          echo "--- Gerando thumbnails para os vídeos existentes ---"
          mkdir -p temp_thumbs
          
          # CORREÇÃO: Usar 'while read' para lidar corretamente com nomes de ficheiros com espaços
          rclone lsf "R2:bia-portfolio-assets/Vídeos" --files-only --exclude "wm_*" | while IFS= read -r video_file; do
            # Ignora linhas em branco que possam surgir
            [ -z "$video_file" ] && continue

            echo "A processar vídeo para thumbnail: ${video_file}"
            # Usa aspas para garantir que o nome do ficheiro é tratado como uma única string
            rclone copyto "R2:bia-portfolio-assets/Vídeos/${video_file}" "./${video_file}"
            
            if [ -f "./${video_file}" ]; then
              thumb_name="${video_file%.*}.jpg"
              ffmpeg -i "./${video_file}" -ss 00:00:01.00 -frames:v 1 -update 1 "temp_thumbs/${thumb_name}" > /dev/null 2>&1
              rm "./${video_file}"
            else
              echo "AVISO: Falha ao descarregar o vídeo '${video_file}'. A ignorar."
            fi
          done
          
          # Sincroniza as thumbnails para limpar as antigas
          rclone sync temp_thumbs "R2:bia-portfolio-assets/Thumbnails" -P

      - name: Gerar data.json, aplicar Marcas de Água e Limpar Ficheiros
        run: |
          echo "--- Executando script Python para processar e limpar media ---"
          mkdir -p scripts/
          curl -L -o scripts/Montserrat.ttf "https://github.com/google/fonts/raw/main/ofl/montserrat/Montserrat%5Bwght%5D.ttf"
          python3 scripts/process_files.py

      - name: Fazer commit e push do data.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          if ! git diff --quiet --exit-code --cached; then
            git commit -m "Atualiza data.json e media [skip ci]"
            git pull --rebase
            git push
          else
            echo "Nenhuma alteração no data.json para fazer commit."
          fi
