# .github/workflows/sync.yml
name: Sincronizar Ficheiros, Gerar JSON e Atualizar Site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

permissions:
  contents: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar rclone
        run: sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Configurar rclone
        env:
          RCLONE_CONF_DATA: ${{ secrets.RCLONE_CONF }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF_DATA" > ~/.config/rclone/rclone.conf

      # --- CORREÇÃO 1: Caminhos de origem e destino corrigidos ---
      - name: Sincronizar Google Drive para Cloudflare R2
        run: |
          # Sincroniza a pasta "Portfólio Bia" do Drive para o bucket "bia-portfolio-assets" no R2
          rclone sync "Drive:Portfólio Bia" "R2:bia-portfolio-assets" --progress --exclude "desktop.ini"

      - name: Instalar FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # --- CORREÇÃO 2: Caminhos corrigidos na geração de thumbnails ---
      - name: Gerar e Sincronizar Thumbnails
        run: |
          echo "A iniciar a geração de thumbnails..."
          mkdir -p temp_thumbs
          
          # Lista todos os vídeos no R2, tratando nomes de ficheiro de forma segura
          rclone lsf "R2:bia-portfolio-assets/Vídeos" --files-only | while IFS= read -r video_file; do
            
            # Remove a extensão para criar o nome base da thumbnail
            thumb_basename=$(basename "$video_file" | sed 's/\.[^.]*$//')
            thumb_filename="${thumb_basename}.jpg"
            local_thumb_path="temp_thumbs/${thumb_filename}"
            
            # Verifica se a thumbnail já existe no R2
            if ! rclone lsf "R2:bia-portfolio-assets/thumbs/" | grep -q "^${thumb_filename}$"; then
              echo "A gerar thumbnail para: ${video_file}"
              
              # Cria um nome de ficheiro temporário único para evitar conflitos
              temp_video_file="temp_${RANDOM}.mp4"

              # Descarrega o vídeo para o ficheiro temporário
              rclone copyto "R2:bia-portfolio-assets/Vídeos/${video_file}" "$temp_video_file"
              
              # Comando FFmpeg com mais logs e tolerância a erros
              # -v error: só mostra erros
              # -y: substitui o ficheiro de saída se existir
              if ffmpeg -v error -y -i "$temp_video_file" -ss 00:00:01 -vframes 1 "$local_thumb_path"; then
                echo "Thumbnail gerada com sucesso para ${video_file}"
              else
                echo "AVISO: Falha ao gerar thumbnail para ${video_file}. A ignorar este vídeo."
              fi
              
              # Apaga o vídeo temporário
              rm "$temp_video_file"
            else
              echo "Thumbnail para ${video_file} já existe. A ignorar."
            fi
          done

          echo "Sincronização de thumbnails para o R2..."
          rclone sync temp_thumbs/ "R2:bia-portfolio-assets/thumbs/"