name: Sincronizar Drive, Gerar Thumbs e Dados

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

permissions:
  contents: write # Dá permissão para escrever (fazer commits) no repositório

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar ferramentas e dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg jq unzip python3-pip
          pip3 install Pillow
          curl https://rclone.org/install.sh | sudo bash

      - name: Configurar rclone
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf

      - name: Sincronizar Google Drive para Cloudflare R2
        run: |
          echo "A sincronizar Google Drive para R2..."
          # Exclui as pastas geradas para não as apagar acidentalmente do R2
          rclone sync "Drive:Portfólio Bia" "R2:bia-portfolio-assets" \
            --exclude "desktop.ini" \
            --exclude "/Thumbnails/**" \
            --exclude "/WatermarkedImages/**" \
            --exclude "/WatermarkedVideos/**" \
            -P
          echo "Sincronização concluída."

      - name: Gerar Thumbnails para Vídeos
        run: |
          echo "A iniciar a geração de thumbnails..."
          mkdir -p temp_thumbs
          
          OLD_IFS="$IFS"
          IFS=$'\n'
          
          # O loop agora tratará cada linha como um único item
          for video_file in $(rclone lsf "R2:bia-portfolio-assets/Vídeos" --files-only ); do
            echo "A processar vídeo: ${video_file}"
            
            # Usar aspas em todas as variáveis com nomes de ficheiros
            rclone copyto "R2:bia-portfolio-assets/Vídeos/${video_file}" "./${video_file}"
            
            if [ -f "./${video_file}" ]; then
              thumb_name="${video_file%.*}.jpg"
              
              # Comando ffmpeg melhorado com a opção -update e aspas
              ffmpeg -i "./${video_file}" -ss 00:00:01.00 -frames:v 1 -update 1 "temp_thumbs/${thumb_name}"
              
              rm "./${video_file}"
            else
              echo "AVISO: Falha ao descarregar o vídeo '${video_file}'. A ignorar."
            fi
          done
          
          IFS="$OLD_IFS"
          
          # --- ALTERAÇÃO PRINCIPAL AQUI ---
          # O caminho de destino foi atualizado para a nova pasta "Thumbnails"
          rclone sync temp_thumbs "R2:bia-portfolio-assets/Thumbnails" -P
          echo "Thumbnails sincronizadas para a pasta Thumbnails."

      - name: Gerar o ficheiro data.json com marcas de água
        run: |
          echo "A gerar data.json e a aplicar marcas de água..."
          # Adiciona a fonte necessária para o script Python
          git clone https://github.com/google/fonts.git --depth 1
          mkdir -p scripts/
          
          # Copia o ficheiro de fonte variável correto e renomeia-o
          cp "fonts/ofl/montserrat/Montserrat[wght].ttf" "scripts/Montserrat.ttf"
          echo "Fonte variável Montserrat copiada para scripts/Montserrat.ttf"
          
          python3 scripts/process_files.py
          echo "data.json gerado e media com marca de água enviada."

      - name: Fazer commit e push do data.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          # Verifica se há alterações antes de fazer commit para evitar commits vazios
          if ! git diff --quiet --exit-code --cached; then
            git commit -m "Atualiza data.json e media [skip ci]"
            git push
          else
            echo "Nenhuma alteração no data.json para fazer commit."
          fi
