name: Sync, Process and Deploy Portfolio Assets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 
      
    env:
      TZ: Europe/Lisbon
      RCLONE_VERSION: "v1.68.0" 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- ETAPA DE CACHING E CONFIGURAÇÃO ---
      
      - name: Cache for apt packages
        id: cache-apt
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/sync.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Cache for pip packages
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache for rclone binary
        id: cache-rclone
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/rclone
          key: ${{ runner.os }}-rclone-${{ env.RCLONE_VERSION }}
          restore-keys: |
            ${{ runner.os }}-rclone-

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ffmpeg jq libjpeg-dev zlib1g-dev libwebp-dev libfreetype6-dev curl unzip
      
      - name: Install Rclone
        if: steps.cache-rclone.outputs.cache-hit!= 'true'
        run: |
          curl -O https://downloads.rclone.org/v1.68.0/rclone-v1.68.0-linux-amd64.zip
          unzip rclone-v1.68.0-linux-amd64.zip
          sudo mv rclone-v1.68.0-linux-amd64/rclone /usr/local/bin/
          sudo chmod 755 /usr/local/bin/rclone
          rm -rf rclone-*

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      # --- ETAPA DE EXECUÇÃO ---

      - name: Setup Rclone Config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      - name: Generate R2 Manifest
        run: python scripts/generate_manifest.py

      - name: Sync from Drive to Local
        run: |
          mkdir -p./local_drive
          rclone copy "Drive:Portfólio Bia"./local_drive -v --exclude "/Thumbnails/**" --exclude "desktop.ini"

      - name: Process Assets
        run: python scripts/process_assets.py

      - name: Sync Processed Files to R2
        run: |
          rclone sync./output "R2:bia-portfolio-assets" -v --fast-list --checksum

      - name: Upload Processing Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: processing-logs
          path: "./output/success.log\n./output/failure.log"
          retention-days: 7