# .github/workflows/sync.yml
name: Sincronizar Ficheiros, Gerar JSON e Atualizar Site

on:
  workflow_dispatch: # Permite execução manual
  schedule:
    - cron: '0 20 * * *' # Executa todos os dias às 20:00 UTC

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar rclone
        run: sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Configurar rclone
        env:
          RCLONE_CONF_DATA: ${{ secrets.RCLONE_CONF }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF_DATA" > ~/.config/rclone/rclone.conf

      - name: Sincronizar Google Drive para Cloudflare R2
        run: |
          # Substitua 'Drive:Bia' pelo seu remote do Drive e pasta principal
          rclone sync Drive:Bia R2:bia --progress

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Gerar o ficheiro data.json
        run: python scripts/generate_data_json.py

      - name: Fazer commit e push do data.json
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@users.noreply.github.com'
          git add data.json
          if ! git diff --staged --quiet; then
            git commit -m "Atualizar data.json com novos ficheiros"
            git push
          else
            echo "Nenhuma alteração no data.json. Nada para fazer commit."
          fi
