name: Sincronizar Media, Gerar Dados e Manifesto

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19,20 * * *'

permissions:
  contents: write

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Europe/Lisbon'
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar ferramentas e dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg jq
          pip3 install Pillow
          curl https://rclone.org/install.sh | sudo bash

      - name: Configurar rclone
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf

      - name: Sincronizar Google Drive para Cloudflare R2
        run: |
          echo "--- Sincronizando Drive -> R2 (protegendo a pasta Thumbnails) ---"
          rclone sync "Drive:Portfólio Bia" "R2:bia-portfolio-assets" --exclude "/Thumbnails/**" --exclude "desktop.ini" -v

      - name: Gerar Thumbnails Incrementais para Vídeos Novos
        run: python3 scripts/thumbnail_generator.py

      - name: Aplicar Marcas de Água e Otimizar Imagens
        run: |
          echo "--- Processando Imagens (Fotografias e Designs) ---"
          mkdir -p scripts/
          curl -L -o scripts/Montserrat-SemiBold.ttf "https://github.com/google/fonts/raw/main/ofl/montserrat/static/Montserrat-SemiBold.ttf"
          python3 scripts/process_images.py

      - name: Aplicar Marcas de Água a Vídeos
        run: |
          echo "--- Processando Vídeos ---"
          python3 scripts/process_videos.py
      
      - name: Gerar data.json e Manifesto de Ficheiros
        run: |
          echo "--- Gerando data.json e manifesto final do R2 ---"
          python3 scripts/generate_final_data.py

      - name: Fazer commit e push de alterações
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json r2_file_manifest.txt
          if ! git diff --quiet --exit-code --cached; then
            git commit -m "Atualiza data.json e manifesto [skip ci]"
            git pull --rebase
            git push
          else
            echo "Nenhuma alteração para fazer commit."
          fi