# .github/workflows/sync.yml

name: Processar e Sincronizar Portfólio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-and-process:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar e fazer cache de dependências Apt
        uses: awalsh128/cache-apt-pkgs-action@v1.5.0
        with:
          packages: ffmpeg libimage-exiftool-perl
          version: 1.0

      - name: Cache para dependências Pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install opencv-python-headless

      - name: Instalar e Configurar Rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          cat << EOF > ~/.config/rclone/rclone.conf
          ${{ secrets.RCLONE_CONF }}
          EOF
          
      - name: Executar Pipeline Principal
        run: python3 main.py

      # --- CORREÇÃO DE LÓGICA ---
      # PASSO 1: Fazer o upload de TODOS os ficheiros processados (imagens, vídeos, thumbnails )
      - name: Sincronizar Ativos Processados para o R2
        run: |
          echo "A sincronizar todos os ativos processados para o R2..."
          rclone sync processed_assets/ R2:bia-portfolio-assets --progress -v

      # PASSO 2: Gerar o manifesto DEPOIS do upload estar completo
      - name: Gerar Manifesto de Ficheiros do R2
        run: |
          echo "A gerar o manifesto de ficheiros a partir do R2..."
          # O rclone_handler.py tem a função para isto, mas podemos chamá-la aqui
          # para garantir a ordem. Ou, mais simples, executar o comando diretamente.
          rclone lsf -R R2:bia-portfolio-assets > r2_file_manifest.txt

      # PASSO 3: Copiar os ficheiros de dados e manifesto para a raiz do R2
      - name: Copiar data.json e Manifesto para a Raiz do R2
        run: |
          echo "A copiar data.json e r2_file_manifest.txt para a raiz do R2..."
          rclone copyto data.json R2:bia-portfolio-assets/data.json --no-check-dest -v
          rclone copyto r2_file_manifest.txt R2:bia-portfolio-assets/r2_file_manifest.txt --no-check-dest -v

      # PASSO 4: Fazer o commit dos ficheiros para o repositório Git
      - name: Fazer Commit e Push dos Ficheiros de Manifesto para o Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json r2_file_manifest.txt || echo "Nenhum ficheiro de manifesto para adicionar."
          
          if ! git diff --staged --quiet; then
            git commit -m "CI: Atualiza data.json e manifesto R2 [skip ci]"
            git push
          else
            echo "Nenhuma alteração nos ficheiros de manifesto para fazer commit."
          fi
