# .github/workflows/sync.yml

name: Processar e Sincronizar Portfólio

on:
  push:
    branches:
      - main # Executa em cada push para o branch principal
  workflow_dispatch: # Permite a execução manual a partir da interface do GitHub

jobs:
  sync-and-process:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache para dependências Pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Instalar e fazer cache de dependências Apt
        uses: awalsh128/cache-apt-pkgs-action@v1.5.0
        with:
          packages: ffmpeg libimage-exiftool-perl
          version: 1.0

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar e Configurar Rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          cat << EOF > ~/.config/rclone/rclone.conf
          ${{ secrets.RCLONE_CONF }}
          EOF
          
      - name: Executar Pipeline Principal
        run: python3 main.py

      # --- CORREÇÃO: Adicionar passo para copiar os manifestos para o R2 ---
      - name: Copiar ficheiros de manifesto para o R2
        run: |
          echo "A copiar data.json e r2_file_manifest.txt para o R2..."
          # O comando 'copyto' copia ficheiros individuais para o destino.
          # A flag --no-check-dest impede que o rclone verifique se o ficheiro já existe,
          # simplesmente sobrescrevendo-o, o que é mais rápido.
          rclone copyto data.json R2:bia-portfolio-assets/data.json --no-check-dest -v
          rclone copyto r2_file_manifest.txt R2:bia-portfolio-assets/r2_file_manifest.txt --no-check-dest -v

      - name: Configurar Git para o bot
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fazer commit e push dos ficheiros de manifesto
        run: |
          git add data.json r2_file_manifest.txt || echo "Nenhum ficheiro novo para adicionar."
          
          if ! git diff --staged --quiet; then
            git commit -m "CI: Atualiza data.json e manifesto R2"
            git push
          else
            echo "Nenhuma alteração nos ficheiros de manifesto para fazer commit."
          fi
