name: Sincronizar, Processar e Aplicar Marca de Água

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-and-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências do sistema e Python
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libjpeg-dev zlib1g-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar e configurar Rclone
        env:
          RCLONE_CONF: ${{ secrets.rclone_conf }}
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf

      - name: Executar o pipeline de processamento
        run: python3 run_processing.py

      - name: Sincronizar ficheiros processados para o R2
        run: |
          # CORREÇÃO: Aponta para o bucket de destino correto e exclui ficheiros.log
          rclone sync processed_assets/ R2:bia-portfolio-assets --exclude "*.log" -v