name: Sincronizar Drive, Gerar Thumbs e Dados

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar ferramentas e a versão mais recente do rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg jq unzip
          curl https://rclone.org/install.sh | sudo bash

      - name: Configurar rclone
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf

      - name: Sincronizar Google Drive para Cloudflare R2
        run: |
          echo "A sincronizar Google Drive para R2..."
          rclone sync "Drive:Portfólio Bia" "R2:bia-portfolio-assets" --exclude "desktop.ini" -P
          echo "Sincronização concluída."

      - name: Gerar Thumbnails para Vídeos
        run: |
          echo "A iniciar a geração de thumbnails..."
          mkdir -p temp_thumbs
          
          rclone lsf "R2:bia-portfolio-assets/Vídeos" --files-only | while read -r video_file; do
            echo "A processar vídeo: ${video_file}"
            rclone copyto "R2:bia-portfolio-assets/Vídeos/${video_file}" "./${video_file}"
            if [ -f "./${video_file}" ]; then
              thumb_name="${video_file%.*}.jpg"
              ffmpeg -i "./${video_file}" -ss 00:00:01.00 -frames:v 1 "temp_thumbs/${thumb_name}"
              rm "./${video_file}"
            fi
          done
          
          rclone sync temp_thumbs "R2:bia-portfolio-assets/_thumbnails" -P
          echo "Thumbnails sincronizadas."

      - name: Gerar o ficheiro data.json
        run: |
          echo "A gerar data.json..."
          python3 scripts/process_files.py
          echo "data.json gerado."

      - name: Fazer commit e push do data.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          git diff --quiet --exit-code --cached || git commit -m "Atualiza data.json [skip ci]"
          git push
